[package]
name = "zrunner"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
anyhow.workspace = true
base64.workspace = true
chrono.workspace = true
libc.workspace = true
serde.workspace = true
serde_json.workspace = true
ulid.workspace = true
zrunner-core.workspace = true
zrunner-protocol.workspace = true
